# Generated by Django 4.2.7 on 2023-11-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_profile_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="profiles/user-default.png",
                null=True,
                upload_to="profiles/",
            ),
        ),
    ]
